name: caffinet_app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.0.0

  http: ^1.5.0
  get_it: ^7.7.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
